---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./amd-gpu.yaml
  - ./certmanager.yaml
  - ./coroot.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./gadget.yaml
  - ./goldpinger.yaml
  - ./grafana.yaml
  - ./ha.yaml
  - ./homepage.yaml
  - ./ingress-nginx.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./pgadmin.yaml
  - ./prometheus.yaml
  - ./reloader.yaml
  - ./replicator.yaml
  - ./snapshotter.yaml
  - ./tns-csi.yaml
  - ./victoriametrics.yaml
