---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tns-csi
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/fenio/tns-csi.git
  ref:
    branch: main
