---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kyoo
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: private
  tls:
    - hosts:
        - "kyoo.${SECRET_DOMAIN}"
  rules:
    - host: "kyoo.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kyoo-api
                port:
                  number: 3567
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: kyoo-api
                port:
                  number: 3567
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: kyoo-transcoder
                port:
                  number: 7666
          - path: /scanner
            pathType: Prefix
            backend:
              service:
                name: kyoo-scanner
                port:
                  number: 4389
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: kyoo-auth
                port:
                  number: 4568
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: kyoo-auth
                port:
                  number: 4568
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kyoo-front
                port:
                  number: 8901
