---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-webui
  namespace: flux-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Flux
    gethomepage.dev/icon: git.svg
spec:
  ingressClassName: private
  tls:
    - hosts:
        - "flux.${SECRET_DOMAIN}"
  rules:
    - host: "flux.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flux-operator
                port:
                  number: 9080
